_wandb:
    value:
        cli_version: 0.25.0
        e:
            ka0r97hg2zel24auav14q7r79oztdop1:
                apple:
                    ecpuCores: 4
                    gpuCores: 7
                    memoryGb: 8
                    name: Apple M1
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "10737418240"
                codePath: scripts/HER.py
                codePathLocal: scripts/HER.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "236467884032"
                email: hakonts@icloud.com
                executable: /Users/hakonstoren/Python_i_VSCODE/Cogito/Depptactics-arena/deeptactics-arena/.venv/bin/python3
                git:
                    commit: 2193ff21b9d3dfa307f57e667e034134fdb09c4c
                    remote: https://github.com/CogitoNTNU/deeptactics-arena.git
                host: dhcp-10-24-106-239.wlan.ntnu.no
                memory:
                    total: "8589934592"
                os: macOS-26.1-arm64-arm-64bit
                program: /Users/hakonstoren/Python_i_VSCODE/Cogito/Depptactics-arena/deeptactics-arena/scripts/HER.py
                python: CPython 3.12.11
                root: /Users/hakonstoren/Python_i_VSCODE/Cogito/Depptactics-arena/deeptactics-arena
                startedAt: "2026-02-19T17:52:33.541876Z"
                writerId: ka0r97hg2zel24auav14q7r79oztdop1
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
                - 2
                - 3
            "2":
                - 1
                - 2
                - 3
            "3":
                - 35
                - 41
            "4": 3.12.11
            "5": 0.25.0
            "12": 0.25.0
            "13": darwin-arm64
