network:
  encoder_type: cnn
  input_shape: [8, 8, 111]
  hidden_shape: 256
  legal_actions: 4672
  num_layers: 4
  stem:
    num_residual_blocks: 32
    block_size: 256
  head:
    hidden_blocks: 1
train:
  learning_rate: 0.0005
  batch_size: 512
  num_epochs: 10
  num_episodes: 2_000_000
  min_replay_size: 10_000
  max_replay_size: 200_000
  num_batches: 16
  T_0 : 1000
mcts:
  cpuct: 2
  pi_temp: 1.5
  dirichlet_alpha: 0.03
  epsilon: 0.25

env_name: chess