network:
  encoder_type: mlp
  input_shape: 18
  hidden_shape: 128
  legal_actions: 9
  num_layers: 4
  stem:
    num_residual_blocks: 1
    block_size: 128
  head:
    hidden_blocks: 4
train:
  learning_rate: 0.001
  batch_size: 32
  num_epochs: 3
  num_episodes: 200
  min_replay_size: 500
  max_replay_size: 10_000
  num_batches: 100
  num_parallel_games: 4
mcts:
  cpuct: 10
  pi_temp: 1
  exploration_moves: 4
  epsilon: 0.25
  num_simulations: 200

env_name: tic_tac_toe