network:
  encoder_type: cnn
  input_shape: [6, 7, 2]
  hidden_shape: 128
  legal_actions: 7
  num_layers: 4
  stem:
    num_residual_blocks: 32
    block_size: 128
  head:
    hidden_blocks: 2
train:
  learning_rate: 0.02
  batch_size: 64
  num_epochs: 10
  num_episodes: 2_000
  min_replay_size: 2_000
  max_replay_size: 500_000
  num_batches: 10
mcts:
  cpuct: 4
  pi_temp: 1
  epsilon: 0.25

env_name: connect_four